[project]
name = "redes-neurais"
version = "0.1.0"
description = "Projeto de Redes Neurais para a disciplina de TTI"
requires-python = ">=3.12"
dependencies = [
    "gensim>=4.4.0",
    "ipykernel",
    "jupyter",
    "kagglehub",
    "matplotlib",
    "opencv-python",
    "pandas",
    "requests",
    "scikit-learn",
    "seaborn",
    "torch",
    "torchvision",
    "tqdm",
    "unidecode>=1.4.0",
]
