spring.application.name=parking-control
# URL do DB
spring.datasource.url=jdbc:mariadb://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
# Username
spring.datasource.username=root
# Senha para o user
spring.datasource.password=${MYSQL_ROOT_PASSWORD}
# Atualiza o db automaticamente com ações como mapear entidades
spring.jpa.hibernate.ddl-auto=update
